name: Test wallet

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    container: robot101/computational-workflows:latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
             root/shared/py.test-3
