name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      uses: docker://robot101/computational-workflows:latest
      with:
        args: python3 -m pytest
