name: Test wallet

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        uses: docker://robot101/computational-workflows
        run: |
          python3 -m pytest
